import { Component } from '@angular/core';
import * as csv from 'csvtojson'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'dict';
  order: 'keyDescOrder' | 'valueAscOrder' | 'originalOrder' | 'keyAscOrder' = 'originalOrder';
  words = [
    "Abandon",
    "Abrasive",
    "Abreast",
    "Abridge",
    "Abstruse",
    "Accentuate",
    "Accord",
    "Acerbic",
    "Acquisitive",
    "Activism",
    "Acumen",
    "Acute",
    "Acute",
    "Adroit",
    "Adulation",
    "Aesthetic",
    "Affable",
    "Affectation",
    "Aghast",
    "Alacrity",
    "Alienate",
    "Aloof",
    "Ambiguity",
    "Ambivalent",
    "Ameliorate",
    "Amiable",
    "Amuse",
    "Anachronism",
    "Antagonistic",
    "Antedate",
    "Antiquity",
    "Antithesis",
    "Apathy",
    "Aplomb",
    "Apologist",
    "Apposite",
    "Appropriate",
    "Arbitrary",
    "Arcane",
    "Arduous",
    "Articulate",
    "Assertive",
    "Assiduous",
    "Astonish",
    "Astound",
    "Attainment",
    "Attribute",
    "Augment",
    "Austerity",
    "Aversion",
    "Avert",
    "Banal",
    "Banish",
    "Bearing",
    "Befriend",
    "Beguile",
    "Beguile",
    "Beguile",
    "Beholden",
    "Belie",
    "Bemuse",
    "Benign",
    "Betray",
    "Bias",
    "Blemish",
    "Blight",
    "Blithe",
    "Blunt",
    "Bogus",
    "Bolster",
    "Boon",
    "Braggart",
    "Brandish",
    "Brazen",
    "Brevity",
    "Bridle",
    "Bucolic",
    "Buoyancy",
    "Calamitous",
    "Callous",
    "Calumny",
    "Canny",
    "Canonize",
    "Caprice",
    "Catastrophe",
    "Cerebral",
    "Check",
    "Cherish",
    "Circumscribe",
    "Circumstantial",
    "Clangor",
    "Clearheaded",
    "Clerical",
    "Clerical",
    "Cloak",
    "Clumsy",
    "Coalesce",
    "Cogent",
    "Coherent",
    "Collusion",
    "Commensurate",
    "Commonplace",
    "Compel",
    "Complacent",
    "Complementary",
    "Compliance",
    "Conditional",
    "Condone",
    "Confound",
    "Consensus",
    "Conspicuous",
    "Contemporary",
    "Contemptuous",
    "Contend",
    "Contend",
    "Contend",
    "Contentment",
    "Conundrum",
    "Convoluted",
    "Cope",
    "Copious",
    "Corroborate",
    "Counterfeit",
    "Counterintuitive",
    "Counterproductive",
    "Cow",
    "Crafty",
    "Crestfallen",
    "Cunning",
    "Cursory",
    "Curtail",
    "Cynical",
    "Daunt",
    "Debacle",
    "Debase",
    "Debunk",
    "Deceit",
    "Deceptive",
    "Defamatory",
    "Deferential",
    "Deft",
    "Defy",
    "Deleterious",
    "Delineate",
    "Demur",
    "Denigrate",
    "Derivative",
    "Detrimental",
    "Devious",
    "Devolve",
    "Didactic",
    "Diffident",
    "Diffuse",
    "Disaffection",
    "Disapprobation",
    "Discern",
    "Discomfit",
    "Discount",
    "Discredit",
    "Discrepancy",
    "Disentangle",
    "Disgruntle",
    "Disintegrate",
    "Disinterested",
    "Dislocation",
    "Dismantle",
    "Disparate",
    "Dispassionate",
    "Dispense",
    "Disquiet",
    "Dissemble",
    "Disseminate",
    "Dissimilar",
    "Dissolution",
    "Distill",
    "Distort",
    "Divergent",
    "Doctrinaire",
    "Dogmatic",
    "Dubious",
    "Duplicity",
    "Dynamism",
    "Eclectic",
    "Eclipse",
    "Ecstatic",
    "Efficacy",
    "Egoism",
    "Egotist",
    "Elate",
    "Elevate",
    "Eloquence",
    "Elusive",
    "Empathy",
    "Emulate",
    "Enchant",
    "Endanger",
    "Endorse",
    "Enfeeble",
    "Engage",
    "Enigmatic",
    "Entail",
    "Entreaty",
    "Entrench",
    "Ephemeral",
    "Equitable",
    "Equivocal",
    "Erode",
    "Erratic",
    "Erroneous",
    "Erstwhile",
    "Estrange",
    "Euphoric",
    "Evanescent",
    "Evasive",
    "Exacerbate",
    "Exacting",
    "Exigent",
    "Exotic",
    "Expedient",
    "Explicit",
    "Exploit",
    "Exposition",
    "Extant",
    "Extraneous",
    "Extravagance",
    "Factual",
    "Fastidious",
    "Feckless",
    "Feeble",
    "Fester",
    "Fickle",
    "Fixate",
    "Fleeting",
    "Florid",
    "Flourish",
    "Flout",
    "Foreground",
    "Foresight",
    "Forestall",
    "Forgo",
    "Forsake",
    "Fortuitous",
    "Fractious",
    "Fringe",
    "Frivolous",
    "Frugality",
    "Futile",
    "Galvanize",
    "Gawky",
    "Germane",
    "Global",
    "Gloom",
    "Goosebumps",
    "Gracious",
    "Gratify",
    "Hackneyed",
    "Harbinger",
    "Harmonious",
    "Heed",
    "Herald",
    "Heterodox",
    "Hidebound",
    "Hindrance",
    "Homogeneity",
    "Hortatory",
    "Humdrum",
    "Hyperbole",
    "Hypocrite",
    "Iconoclastic",
    "Illiberal",
    "Illuminate",
    "Imitate",
    "Imminent",
    "Immunity",
    "Immure",
    "Immutable",
    "Impair",
    "Impartial",
    "Impecunious",
    "Impediment",
    "Impenetrable",
    "Imperative",
    "Impetuous",
    "Impetus",
    "Implicit",
    "Impolitic",
    "Improvisation",
    "Imprudent",
    "Impudence",
    "Impulsive",
    "Inalienable",
    "Inarticulate",
    "Incendiary",
    "Incensed",
    "Incongruous",
    "Inconsequential",
    "Inconsiderable",
    "Indebted",
    "Indecision",
    "Indecorous",
    "Indefatigable",
    "Indemnify",
    "Indifferent",
    "Indiscernible",
    "Indolent",
    "Industrious",
    "Inestimable",
    "Infallible",
    "Informed",
    "Ingenious",
    "Inhibit",
    "Inimical",
    "Injudicious",
    "Innocuous",
    "Inscrutable",
    "Insightful",
    "Insipid",
    "Insolence",
    "Integrate",
    "Intelligible",
    "Interchangeable",
    "Intermediary",
    "Interminable",
    "Interweave",
    "Intimately",
    "Intractable",
    "Intransigent",
    "Intrigue",
    "Intrinsic",
    "Invaluable",
    "Inveigle",
    "Invigorate",
    "Involved",
    "Irascible",
    "Irksome",
    "Ironic",
    "Irrefutable",
    "Irremediable",
    "Irresolute",
    "Jettison",
    "Judicious",
    "Juxtaposition",
    "Keen",
    "Kindred",
    "Laborious",
    "Lament",
    "Latitude",
    "Laudable",
    "Lax",
    "Layperson",
    "Lionize",
    "Long-Winded",
    "Loquacious",
    "Lucid",
    "Lucrative",
    "Lure",
    "Lurid",
    "Magnanimity",
    "Makeshift",
    "Maladroit",
    "Malign",
    "Malignant",
    "Malleable",
    "Manacle",
    "Manipulate",
    "Marginalize",
    "Mask",
    "Materialize",
    "Meager",
    "Melding",
    "Menace",
    "Mercurial",
    "Meticulous",
    "Mimic",
    "Misnomer",
    "Mitigate",
    "Modish",
    "Monotony",
    "Morbid",
    "Mortify",
    "Mounting",
    "Multifaceted",
    "Mundane",
    "Murky",
    "Naive",
    "Narcissism",
    "Narrative",
    "Nascent",
    "Nettles",
    "Nonchalant",
    "Normative",
    "Novel",
    "Noxious",
    "Obdurate",
    "Objurgate",
    "Obligate",
    "Obscure",
    "Obsequious",
    "Obsolete",
    "Obstinate",
    "Obviate",
    "Omnipresent",
    "Omniscient",
    "Opportunism",
    "Optimistic",
    "Opulent",
    "Original",
    "Outmoded",
    "Overly",
    "Overshadow",
    "Overstate",
    "Panacea",
    "Panache",
    "Partial",
    "Partiality",
    "Partisan",
    "Passable",
    "Pastoral",
    "Patent",
    "Peculiarity",
    "Pedestrian",
    "Pejorative",
    "Pellucidity",
    "Penchant",
    "Penetrate",
    "Penitent",
    "Perfunctory",
    "Peripheral",
    "Pernicious",
    "Perseverance",
    "Persistence",
    "Personify",
    "Perspicacity",
    "Pessimism",
    "Phlegmatic",
    "Picturesque",
    "Pithy",
    "Pivotal",
    "Placid",
    "Plastic",
    "Plod",
    "Polemic",
    "Portend",
    "Pragmatism",
    "Precarious",
    "Precedence",
    "Precocious",
    "Predicament",
    "Predominant",
    "Preeminent",
    "Premonition",
    "Presage",
    "Prescience",
    "Pressing",
    "Presume",
    "Pretension",
    "Pretentious",
    "Prevalent",
    "Prevaricate",
    "Pristine",
    "Probity",
    "Prodigal",
    "Profligate",
    "Profound",
    "Prolix",
    "Promulgate",
    "Propagate",
    "Prophetic",
    "Propped",
    "Prosaic",
    "Provincial",
    "Provoke",
    "Proxy",
    "Prudent",
    "Pugnacious",
    "Punctilious",
    "Puzzle",
    "Quandary",
    "Quirky",
    "Quixotic",
    "Quotidian",
    "Rallying",
    "Ramble",
    "Rationalize",
    "Recondite",
    "Recrudesce",
    "Redemption",
    "Redouble",
    "Redundant",
    "Refuge",
    "Rein",
    "Rejuvenate",
    "Relish",
    "Remedial",
    "Replicate",
    "Repudiate",
    "Residual",
    "Resolute",
    "Restive",
    "Restrain",
    "Resurgent",
    "Reverence",
    "Rhapsody",
    "Ridicule",
    "Row",
    "Ruinous",
    "Ruminate",
    "Salubrious",
    "Sanguine",
    "Sartorial",
    "Scanty",
    "Scathe",
    "Schism",
    "Scintillating",
    "Scornful",
    "Scrupulous",
    "Scrutinize",
    "Scuffle",
    "Flattery",
    "Self-Righteous",
    "Serendipity",
    "Sham",
    "Shirk",
    "Shrewd",
    "Sinister",
    "Skeptic",
    "Skittish",
    "Slighted",
    "Snare",
    "Sparing",
    "Sporadic",
    "Spurious",
    "Stanched",
    "Staple",
    "Startling",
    "Stigmatize",
    "Stimulate",
    "Stingy",
    "Stun",
    "Substantiate",
    "Subtle",
    "Subversion",
    "Sullen",
    "Superfluous",
    "Supersede",
    "Supplement",
    "Supplication",
    "Surly",
    "Surrogate",
    "Susceptible",
    "Sycophant",
    "Synoptic",
    "Syntactical",
    "Synthesize",
    "Taciturn",
    "Tactless",
    "Temperate",
    "Tendentious",
    "Tepid",
    "Thrift",
    "Timorous",
    "Tranquil",
    "Transcend",
    "Transgression",
    "Transitory",
    "Trifle",
    "Trite",
    "Trivial",
    "Ubiquitous",
    "Uncultivated",
    "Undemonstrative",
    "Undermine",
    "Underscore",
    "Understate",
    "Undo",
    "Unintelligible",
    "Unmistakable",
    "Unprecedented",
    "Unpremeditated",
    "Unpretentious",
    "Unpropitious",
    "Unseemly",
    "Unsound",
    "Untapped",
    "Utterly",
    "Venal",
    "Veracious",
    "Vestigial",
    "Viable",
    "Vigilance",
    "Vindicate",
    "Virulence",
    "Vociferous",
    "Voluble",
    "Wanting",
    "Wary",
    "Wilful",
    "Witty",
    "Woo",
    "Zealot"
  ]
  meanings = [
    "complete lack of inhibition or restraint.",
    "showing little concern for the feelings of others; harsh.",
    "up to date with the latest news, ideas, or information",
    "shorten (a piece of writing) without losing the sense.",
    "difficult to understand; obscure.",
    "to make (something) more prominent or noticeable",
    "an official agreement or treaty.",
    "sharply or bitingly critical, sarcastic, or ironic in temper, mood, or tone",
    "excessively interested in acquiring money or material things.",
    "the policy or action of using vigorous campaigning to bring about political or social change.",
    "superior insight; quickness and shrewdness of judgment, especially in practical matters.",
    "present or experienced to a severe or intense degree.",
    "having or showing a perceptive understanding or insight; shrewd.",
    "clever or skillful in using the hands or mind.",
    "obsequious flattery; excessive admiration or praise.",
    "concerned with beauty or the appreciation of beauty.",
    "friendly, good-natured, or easy to talk to.",
    "behavior, speech, or writing that is artificial and designed to impress.",
    "filled with horror or shock.",
    "brisk and cheerful readiness.",
    "cause (someone) to feel isolated or estranged.",
    "conspicuously uninvolved and uninterested, typically through distaste.",
    "the quality of being open to more than one interpretation; inexactness.",
    "having mixed feelings or contradictory ideas about something or someone.",
    "make (something bad or unsatisfactory) better, improve",
    "having or displaying a friendly and pleasant manner.",
    "cause (someone) to find something funny; entertain.",
    "belonging to a period other than that being portrayed.",
    "showing or feeling active opposition or hostility toward someone or something.",
    "precede in time; come before (something) in date.",
    "the ancient past, especially the period before the middle ages.",
    "a contrast or opposition between two things.",
    "lack of interest, enthusiasm, or concern.",
    "complete and confident composure or self-assurance",
    "a person who offers an argument in defense of something controversial.",
    "apt in the circumstances or in relation to something.",
    "take (something) for one's own use, typically without the owner's permission.",
    "based on random choice or personal whim, rather than any reason or system.",
    "understood by few; mysterious or secret.",
    "involving or requiring strenuous effort; difficult and tiring.",
    "(of a person or a person's words) having or showing the ability to speak fluently and coherently.",
    "having or showing a confident and forceful personality.",
    "showing great care and perseverance.",
    "surprise or impress (someone) greatly.",
    "shock or greatly surprise.",
    "a thing achieved, especially a skill or educational achievement.",
    "regard something as being caused by (someone or something).",
    "make (something) greater by adding to it; increase.",
    "extreme plainness and simplicity of style or appearance.",
    "a strong dislike or disinclination.",
    "prevent or ward off (an undesirable occurrence).",
    "so lacking in originality as to be obvious and boring.",
    "send (someone) away from a country or place as an official punishment.",
    "relation; relevance.",
    "act as a friend to (someone) by offering help or support.",
    "charm or enchant (someone), sometimes in a deceptive way.",
    "trick (someone) into doing something.",
    "help (time) pass pleasantly.",
    "owing thanks or having a duty to someone in return for help or a service.",
    "(of an appearance) fail to give a true notion or impression of (something); disguise or contradict.",
    "puzzle, confuse, or bewilder (someone).",
    "harmless, kind, gentle",
    "unintentionally reveal; be evidence of.",
    "prejudice in favor of or against one thing, person, or group compared with another, usually in a way considered to be unfair.",
    "spoil the appearance of (something) that is otherwise aesthetically perfect.",
    "have a severely detrimental effect on.",
    "showing a casual and cheerful indifference considered to be callous or improper.",
    "(of a person or remark) uncompromisingly forthright.",
    "not genuine or true; fake.",
    "support or strengthen; prop up.",
    "a thing that is helpful or beneficial.",
    "a person who boasts about achievements or possessions.",
    "wave or flourish (something, especially a weapon) as a threat or in anger or excitement.",
    "bold and without shame. endure an embarrassing or difficult situation by behaving with apparent confidence and lack of shame.",
    "concise and exact use of words in writing or speech.",
    "bring (something) under control; curb.",
    "relating to the pleasant aspects of the countryside and country life.",
    "an optimistic and cheerful disposition.",
    "involving calamity; catastrophic or disastrous.",
    "feeling or showing no sympathy for others",
    "a false and slanderous statement.",
    "having or showing shrewdness and good judgment, especially in money or business matters.",
    "treat or regard as being above reproach or of great significance.",
    "a sudden and unaccountable change of mood or behavior.",
    "an event causing great and often sudden damage or suffering; a disaster.",
    "intellectual rather than emotional or physical.",
    "stop or slow down the progress of (something undesirable).",
    "protect and care for (someone) lovingly.",
    "restrict (something) within limits.",
    "pointing indirectly toward someone's guilt but not conclusively proving it.",
    "a continuous loud banging or ringing sound.",
    "alert and thinking logically and coherently.",
    "(of a job or person) concerned with or relating to work in an office, especially routine documentation and administrative tasks.",
    "relating to the clergy.",
    "hide, cover, or disguise (something).",
    "done awkwardly or without skill or elegance.",
    "come together to form one mass or whole.",
    "(of an argument or case) clear, logical, and convincing.",
    "(of an argument, theory, or policy) logical and consistent.",
    "secret or illegal cooperation or conspiracy, especially in order to cheat or deceive others.",
    "corresponding in size or degree; in proportion.",
    "a trite saying or topic; a platitude, a usual or ordinary thing.",
    "force or oblige (someone) to do something.",
    "showing smug or uncritical satisfaction with oneself or one's achievements.",
    "acting or serving to complete; completing.",
    "unworthy or excessive acquiescence.",
    "subject to one or more conditions or requirements being met; made or granted on certain terms.",
    "accept and allow (behavior that is considered morally wrong or offensive) to continue.",
    "cause surprise or confusion in (someone), especially by acting against their expectations.",
    "a general agreement.",
    "standing out so as to be clearly visible.",
    "living or occurring at the same time.",
    "feeling or expressing angry disgust, as at something unworthy or wicked; scornful.",
    "struggle to surmount (a difficulty or danger).",
    "assert something as a position in an argument.",
    "engage in a competition or campaign in order to win or achieve (something).",
    "a state of happiness and satisfaction.",
    "a confusing and difficult problem or question.",
    "(especially of an argument, story, or sentence) extremely complex and difficult to follow.",
    "(of a person) deal effectively with something difficult.",
    "abundant in supply or quantity.",
    "confirm or give support to (a statement, theory, or finding).",
    "a fraudulent imitation of something else; a forgery.",
    "contrary to intuition or to common-sense expectation (but often nevertheless true).",
    "having the opposite of the desired effect.",
    "cause (someone) to submit to one's wishes by intimidation.",
    "clever at achieving one's aims by indirect or deceitful methods.",
    "sad and disappointed.",
    "having or showing skill in achieving one's ends by deceit or evasion.",
    "hasty and therefore not thorough or detailed.",
    "to make less by or as if by cutting off or away some part",
    "believing that people are motivated by self-interest; distrustful of human sincerity or integrity.",
    "make (someone) feel intimidated or apprehensive.",
    "a sudden collapse into disaster; downfall.",
    "to reduce in value, quality, esteem, or character.",
    "to expose or ridicule the falseness or exaggerations of (a claim, theory, or the like).",
    "the act or practice of misleading, tricking, or cheating.",
    "able or tending to trick or mislead.",
    "causing or tending to cause injury to another's reputation; libelous or slanderous.",
    "respectfully submissive to the desires, opinions, or judgments of others.",
    "capable, quick, and clever in action; skillful; dexterous.",
    "to resist or challenge openly; act against the wishes or decrees of.",
    "harmful or injurious, as to health.",
    "to describe or portray in precise or vivid detail.",
    "raise doubts or objections or show reluctance.",
    "criticize unfairly; disparage.",
    "copied, modeled on, or extracted from something else.",
    "causing harm, disadvantage, or deterioration.",
    "not the straightest, most direct way; winding; roundabout.",
    "(of duties or responsibility) pass to (a body or person at a lower level).",
    "in the manner of a teacher, particularly so as to treat someone in a patronizing way.",
    "modest or shy because of a lack of self-confidence.",
    "spread out over a large area; not concentrated.",
    "a state or feeling of being dissatisfied with the people in authority and no longer willing to support them.",
    "strong disapproval, typically on moral grounds.",
    "to perceive, make out, or detect.",
    "make (someone) feel uneasy or embarrassed.",
    "regard (a possibility, fact, or person) as being unworthy of consideration because it lacks credibility.",
    "to harm the reputation of.",
    "lack of agreement; difference; inconsistency.",
    "to free or become free from entanglement or involvement; extricate.",
    "to make irritably dissatisfied or discontent.",
    "to come apart; break down into component parts or fragments.",
    "having or feeling no interest in something.",
    "disturbance from a proper, original, or usual place or state.",
    "to tear down; take apart.",
    "essentially different and distinct.",
    "without strong feeling or bias; calm; impartial.",
    "to give out or distribute.",
    "lack of mental calm or peace; anxiety; uneasiness.",
    "to disguise or hide behind a false semblance; conceal the true nature or state of.",
    "to spread widely, as though scattering seed.",
    "not alike; different.",
    "debauched living; dissipation.",
    "extract the essential meaning or most important aspects of.",
    "give a misleading or false account or impression of.",
    "deviating, differing, or diverging.",
    "dogmatically adhering to a theory or a school of thought, regardless of its practicality.",
    "asserting beliefs and opinions as though they were proven facts.",
    "having or showing doubt; skeptical.",
    "deceitful speech or action.",
    "the quality of being characterized by vigorous activity and progress.",
    "deriving ideas, style, or taste from a broad and diverse range of sources.",
    "overshadow, outshine",
    "in a condition of extreme delight, overpowering emotion, or religious trance; enraptured.",
    "the ability to produce desired results; effectiveness.",
    "the tendency to evaluate everything in relation to one's own interests; self-centeredness.",
    "a conceited person; braggart.",
    "to make extremely happy or proud; cause to be in elevated spirits.",
    "to raise or lift up to a higher physical position.",
    "skill or ability to use language that impresses or persuades.",
    "hard to perceive, understand, or remember.",
    "the ability to understand and share the feelings of another.",
    "to try to be the same as or better than (another person), especially by imitating.",
    "to put under a magic spell, or as if under a magic spell; bewitch.",
    "to cause to be exposed to danger.",
    "to approve or give support to.",
    "to take away the strength of; make feeble, as from age or disease.",
    "occupy, attract, or involve (someone's interest or attention).",
    "puzzling, mysterious, or inexplicable.",
    "involve (something) as a necessary or inevitable part or consequence.",
    "an earnest or humble request.",
    "establish (an attitude, habit, or belief) so firmly that change is very difficult or unlikely.",
    "lasting for only a short period.",
    "characterized by fairness; just.",
    "open to more than one interpretation; ambiguous.",
    "gradually destroy or be gradually destroyed.",
    "not occurring predictably or consistently; unpredictable.",
    "containing or based on a mistake; incorrect.",
    "of an earlier time; former.",
    "cause (someone) to be no longer close or affectionate to someone; alienate.",
    "having or exhibiting a strong feeling of well-being or elation.",
    "tending to disappear like vapor; vanishing; fleeting.",
    "ambiguous, tending to avoid commitment or self-revelation, especially by responding only indirectly.",
    "make (a problem, bad situation, or negative feeling) worse.",
    "making great demands on one's skill, attention, or other resources.",
    "requiring immediate attention; urgent or critical.",
    "attractive or striking because colorful or out of the ordinary.",
    "a means of attaining an end, especially one that is convenient but considered improper or immoral.",
    "stated fully, clearly, and without equivocation.",
    "make full use of and derive benefit from (a resource).",
    "a comprehensive description and explanation of an idea or theory.",
    "still in existence; current; not extinct, destroyed, or lost.",
    "coming from outside; foreign.",
    "the act or an instance of spending excessively or imprudently.",
    "containing or based upon real or true things.",
    "very attentive to and concerned about accuracy and detail.",
    "weak or incompetent; ineffective.",
    "without strength or vigor, physically, mentally, or morally.",
    "(of a negative feeling or a problem) becoming worse or more intense, especially through long-term neglect or indifference.",
    "quickly changing without reason or warning, especially in affection or allegiance; variable or capricious.",
    "cause (someone) to acquire an obsessive attachment to someone or something.",
    "lasting for a very short time.",
    "elaborately or excessively intricate or complicated.",
    "to make bold and sweeping gestures",
    "openly disregard (a rule, law or convention).",
    "make (something) the most prominent or important feature.",
    "the ability to predict or the action of predicting what will happen or be needed in the future.",
    "to prevent or hinder by taking action beforehand.",
    "omit or decline to take (something pleasant or valuable); go without.",
    "to abandon or desert.",
    "happening or appearing by chance, as a coincidence.",
    "(typically of children) irritable and quarrelsome.",
    "not part of the mainstream; unconventional, peripheral, or extreme.",
    "unworthy of serious consideration or merit; trivial or silly.",
    "prudent or sparing use of resources, especially money.",
    "unlikely to produce or incapable of producing a desired result; ineffective; useless.",
    "to stimulate into awareness or activity.",
    "ungainly; awkward; clumsy.",
    "having relevance to a given matter; pertinent; significant.",
    "relating to or embracing the whole of something, or of a group of things.",
    "to look, feel, or act sullen or despondent",
    "a state of the skin caused by cold, fear, or excitement, in which small bumps appear on the surface as the hairs become erect.",
    "inclined to do what is polite, kind, right, or considerate.",
    "to give pleasure or satisfaction to (someone).",
    "made trite or commonplace by overuse, as an expression or phrase.",
    "a person or thing that announces or signals the approach of another.",
    "characterized by agreement or accord.",
    "to give one's attention to; take notice of.",
    "be a sign that (something) is about to happen.",
    "deviating from an officially approved belief or doctrine, especially in religion.",
    "unwilling or unable to change because of tradition or convention.",
    "someone or something that acts as an obstacle, as to an action or goal.",
    "the quality or state of being all the same or all of the same kind.",
    "urging or exciting to some course of action with strong arguments, appeals, or advice.",
    "lacking variety; dull, monotonous, and commonplace.",
    "exaggerated statements or claims not meant to be taken literally.",
    "one who states or pretends to hold beliefs or principles he or she does not actually practice.",
    "attacking or breaking away from established traditions, beliefs, or values.",
    "lacking tolerance; bigoted.",
    "help to clarify or explain.",
    "to follow the manner or pattern of; attempt to resemble; mimic.",
    "about to happen or likely to happen very soon.",
    "protection or exemption from something, especially an obligation or penalty.",
    "to confine within or as though within walls; shut in.",
    "not subject to change; unchanging or unchangeable.",
    "to weaken, damage, or cause to diminish in value or quality.",
    "not biased or prejudiced; even-handed or objective.",
    "having little or no money.",
    "an obstacle or hindrance.",
    "impossible to understand.",
    "extremely important; urgent; unavoidable.",
    "acting or done quickly and without thought or care.",
    "something that urges or impels; a driving force.",
    "essentially or very closely connected with; always to be found in.",
    "not showing good sense or judgment; unwise or injudicious.",
    "produce or make (something) from whatever is available.",
    "not showing care for the consequences of an action; rash.",
    "the act or condition of being boldly disrespectful; insolence.",
    "motivated by spontaneous wishes and needs rather than careful thought.",
    "not subject to transfer, surrender, or removal, especially one's rights as a citizen.",
    "unable to speak distinctly or express oneself clearly.",
    "tending to stir up conflict.",
    "very angry; enraged.",
    "not in harmony or keeping with the surroundings or other aspects of something.",
    "having no significant effect or result; not important.",
    "unimportant or insignificant.",
    "obligated to another person or persons, as for money or favors.",
    "inability or unwillingness to make a decision.",
    "not in keeping with good taste and propriety; improper.",
    "(of a person or their efforts) persisting tirelessly.",
    "to make compensation to for loss, damage, or expense incurred.",
    "lacking interest or concern; not caring.",
    "impossible to see or clearly distinguish.",
    "wanting to avoid activity or exertion; lazy.",
    "diligent and hard-working.",
    "too great to calculate.",
    "incapable of error.",
    "having or showing knowledge of a particular subject or situation.",
    "(of a person) clever, original, and inventive.",
    "to hold back, restrain, prevent, or tend to do so.",
    "unfriendly; hostile.",
    "lacking in or poor in judgment; rash or unwise.",
    "not capable of causing damage; harmless.",
    "impossible to comprehend or interpret; mysterious.",
    "having or showing an accurate and deep understanding; perceptive.",
    "having a bland or uninteresting flavor; tasteless.",
    "rude or impudent behavior or speech.",
    "to bring together and blend into a whole.",
    "capable of being clearly understood; comprehensible.",
    "of two things, able to be put or used in place of each other.",
    "a person who acts as an agent or mediator between persons, groups, or the like; go-between.",
    "endless or seemingly endless; monotonously long.",
    "blend closely.",
    "in a way that involves detailed knowledge.",
    "not easily controlled, managed, or persuaded.",
    "refusing to alter an idea or a position in response to others' wishes; uncompromising.",
    "to strongly draw the interest of; puzzle; fascinate.",
    "being essential to or of the nature of a thing; inherent.",
    "having a worth too great to estimate or measure; priceless.",
    "to entice or ensnare by clever talk or flattery.",
    "to fill with energy, strength, or life.",
    "difficult to comprehend; complicated.",
    "easily angered or irritated; short-tempered.",
    "causing annoyance; bothersome or tiresome.",
    "happening in the opposite way to what is expected, and typically causing wry amusement because of this.",
    "impossible to disprove; indisputable.",
    "impossible to cure, repair, or correct.",
    "showing or feeling hesitancy; uncertain.",
    "throw or drop (something) from an aircraft or ship.",
    "characterized by or using sound judgment; wise; prudent.",
    "the fact of two things being seen or placed close together with contrasting effect.",
    "extremely sharp; able to cut readily and finely.",
    "similar in kind; related.",
    "requiring considerable effort or perseverance.",
    "a passionate expression of grief or sorrow.",
    "scope for freedom of action or thought.",
    "worthy of praise.",
    "not rigorous, strict, or careful; loose; lenient.",
    "a person without professional or specialized knowledge in a particular subject.",
    "to view or treat (someone) as a celebrity or extraordinary person.",
    "speaking or writing at too great a length, especially in a dull or tiresome way; verbose.",
    "given to talking much or excessively; garrulous.",
    "easy to understand; articulate; clear.",
    "producing monetary gain; profitable.",
    "to attract, as by a desirable quality.",
    "sensational; shocking or dramatic.",
    "generosity or willingness to forgive.",
    "a temporary or improvised arrangement.",
    "not skillful; clumsy; tactless.",
    "to speak badly of; defame; slander.",
    "evil or injurious in intent, effect, or character.",
    "easily influenced; pliable.",
    "restrain, hinder",
    "control or influence (a person or situation) cleverly, unfairly, or unscrupulously.",
    "to exclude or treat as being of no importance, especially so as to divert attention from.",
    "conceal (something) from view.",
    "become actual fact; happen.",
    "low in quantity, extent, strength, or richness; scanty or feeble.",
    "blend; combine.",
    "that which poses a danger or threatens injury or harm; threat.",
    "volatile in temper; changeable; fickle.",
    "carefully attentive to every small detail; painstaking.",
    "to copy or imitate, often playfully or as part of a learning process.",
    "an incorrect or inappropriate name.",
    "to lessen the force, severity, or impact of.",
    "being in or according to current fashion or style; fashionable.",
    "lack of variety and interest; tedious repetition and routine.",
    "in an unhealthy, gloomy mental state; preoccupied with sickness, abnormality, or death.",
    "to subject (someone) to extreme embarrassment, shame, or humiliation.",
    "grow larger or more numerous.",
    "having several aspects or stages; complex or various.",
    "of or pertaining to what is common and everyday; ordinary; commonplace.",
    "not fully explained or understood, especially with concealed dishonesty or immorality.",
    "(of a person or action) showing a lack of experience, wisdom, or judgment.",
    "excessive interest in or admiration of oneself and one's physical appearance.",
    "an account, description, or story, or the oral or written work containing such material.",
    "coming into being or starting to develop.",
    "irritate or annoy (someone).",
    "not showing excitement or anxiety; coolly confident, unflustered, or unworried;casually indifferent.",
    "establishing, relating to, or deriving from a standard or norm, especially of behavior.",
    "new or unusual in an interesting way.",
    "harmful, dangerous, or destructive, especially to health.",
    "stubbornly refusing to change one's opinion or course of action.",
    "to criticize sharply; rebuke vehemently; berate.",
    "to bind legally or morally; constrain.",
    "not important or well known.",
    "obedient or attentive to an excessive or servile degree, fawning",
    "no longer produced or used; out of date.",
    "holding stubbornly to one's own ideas or purposes; unwilling to change.",
    "avoid; prevent.",
    "existing in all places at any given time.",
    "infinite in knowledge; all-knowing.",
    "the taking of opportunities as and when they arise, regardless of planning or principle.",
    "expecting or tending to expect favorable outcomes.",
    "having or displaying wealth or richness.",
    "created directly and personally by a particular artist; not a copy or imitation.",
    "no longer in keeping with current standards or practices; obsolete.",
    "excessively",
    "appear much more prominent or important than.",
    "to inflate the importance of; exaggerate.",
    "a remedy or solution for all diseases, ills, or difficulties; cure-all.",
    "a confidently stylish, dashing, or flamboyant manner.",
    "favoring one side in a dispute above the other; biased.",
    "unfair bias in favor of one thing or person compared with another; favoritism.",
    "devoted to or favoring a particular cause, group, political party, or the like.",
    "just good enough to be acceptable; satisfactory.",
    "of or relating to the country or country life; rural.",
    "easily recognizable; obvious.",
    "the state or fact of being odd or strange.",
    "lacking inspiration or excitement; dull.",
    "expressing contempt or disapproval.",
    "lucid in style or meaning; easily understood.",
    "a strong or habitual liking for something or tendency to do something.",
    "be fully understood or realized by someone.",
    "feeling or showing sorrow and regret for having done wrong; repentant.",
    "done quickly and as a matter of routine; performed without care.",
    "of secondary or minor importance; marginal.",
    "having a very harmful or fatal effect; injurious, deadly, or destructive.",
    "persistence in doing something despite difficulty or delay in achieving success.",
    "firm or obstinate continuance in a course of action in spite of difficulty or opposition.",
    "to be a perfect or typical example of; embody.",
    "keenness of mental perception or grasp; astuteness.",
    "the belief that events will turn out badly; tendency to expect the worst.",
    "not given to shows of emotion or interest; slow to excite.",
    "visually pleasing, enchanting, or unusual; suggestive of a painting.",
    "exactly and concisely appropriate; effective; forceful.",
    "critically important or crucial; on which something is contingent.",
    "calm, smooth, or tranquil.",
    "not genuine; artificial or unnatural.",
    "to move slowly or heavily, as if with weariness or reluctance; trudge.",
    "a strong verbal or written attack on someone or something.",
    "be a sign or warning that (something, especially something momentous or calamitous) is likely to happen.",
    "a practical approach to problems and issues.",
    "dependent on chance; uncertain.",
    "priority in importance, order, or rank.",
    "(of a child) having developed certain abilities or inclinations at an earlier age than is usual or expected.",
    "a difficult, unpleasant, or embarrassing situation.",
    "having or exerting control or power.",
    "surpassing all others; very distinguished in some way.",
    "a strong feeling that something is about to happen, especially something unpleasant.",
    "be a sign or warning of (an imminent event, typically an unwelcome one).",
    "the fact of knowing something in advance; foreknowledge.",
    "requiring quick or immediate action or attention.",
    "take for granted that something exists or is the case.",
    "the use of affectation to impress; ostentatiousness.",
    "attempting to impress by affecting greater importance or merit than is actually possessed.",
    "widespread in a particular area or at a particular time.",
    "speak or act in an evasive way.",
    "in its original condition; unspoilt.",
    "the quality of having strong moral principles; honesty and decency.",
    "spending money or resources freely and recklessly; wastefully extravagant.",
    "recklessly extravagant or wasteful in the use of resources.",
    "(of a subject or idea) demanding deep study or thought.",
    "(of speech or writing) using or containing too many words; tediously lengthy.",
    "promote or make widely known (an idea or cause).",
    "spread and promote (an idea, theory, etc.) widely.",
    "accurately predicting what will happen in the future.",
    "support or keep in position.",
    "commonplace",
    "limited in outlook; narrow-minded.",
    "stimulate or give rise to (a reaction or emotion, typically a strong or unwelcome one) in someone.",
    "a person authorized to act on behalf of another.",
    "acting with or showing care and thought for the future.",
    "eager or quick to argue, quarrel, or fight.",
    "showing great attention to detail or correct behaviour.",
    "cause (someone) to feel confused because they cannot understand something.",
    "a state of perplexity or uncertainty over what to do in a difficult situation.",
    "characterized by peculiar or unexpected traits.",
    "exceedingly idealistic; unrealistic and impractical.",
    "of or occurring every day; daily.",
    "the action or process of coming together to support a person or cause.",
    "talk or write at length in a confused or inconsequential way.",
    "attempt to explain or justify (behaviour or an attitude) with logical reasons, even if these are not appropriate.",
    "(of a subject or knowledge) little known; abstruse.",
    "to break out or appear again after a period of dormancy",
    "the action of saving or being saved from sin, error, or evil.",
    "make or become much greater, more intense, or more numerous.",
    "unnecessarily repetitive.",
    "the state of being safe or sheltered from pursuit, danger, or difficulty.",
    "keep under control; restrain.",
    "give new energy or vigour to; revitalize.",
    "great enjoyment.",
    "giving or intended as a remedy or cure.",
    "make an exact copy of; reproduce.",
    "refuse to accept; reject.",
    "remaining after the greater part or quantity has gone.",
    "admirably purposeful, determined, and unwavering.",
    "(of a person) unable to remain still, silent, or submissive, especially because of boredom or dissatisfaction.",
    "prevent (someone or something) from doing something; keep under control or within limits.",
    "increasing or reviving after a period of little activity, popularity, or occurrence.",
    "deep respect for someone or something.",
    "an effusively enthusiastic or ecstatic expression of feeling.",
    "subject to contemptuous and dismissive language or behaviour.",
    "dispute",
    "disastrous or destructive.",
    "think deeply about something.",
    "health-giving; healthy.",
    "optimistic or positive, especially in an apparently bad or difficult situation.",
    "relating to tailoring, clothes, or style of dress.",
    "small or insufficient in quantity or amount.",
    "harm; injure.",
    "a split or division between strongly opposed sections or parties, caused by differences in opinion or belief.",
    "brilliantly and excitingly clever or skillful.",
    "feeling or expressing contempt or derision.",
    "adhering strictly to standards of ethics or morality; punctilious.",
    "examine or inspect closely and thoroughly.",
    "to take part in a brief, confused fight among a few people.",
    "excessive and insincere praise, given especially to further one's own interests.",
    "having or characterized by a certainty, especially an unfounded one, that one is totally correct or morally superior.",
    "the occurrence and development of events by chance in a happy or beneficial way.",
    "an imitation that is passed as genuine; counterfeit.",
    "avoid or neglect (a duty or responsibility).",
    "having or showing sharp powers of judgement; astute.",
    "giving the impression that something harmful or evil is happening or will happen.",
    "a person inclined to question or doubt accepted opinions.",
    "nervous or excitable; easily scared",
    "insult (someone) by treating or speaking of them without proper respect or attention.",
    "catch or trap (someone).",
    "moderate; economical.",
    "occurring at irregular intervals or only in a few places; scattered or isolated.",
    "not being what it purports to be; false or fake.",
    "stop or restrict (a flow of blood) from a wound.",
    "main or important, especially in terms of consumption.",
    "very surprising, astonishing, or remarkable.",
    "describe or regard as worthy of disgrace or great disapproval.",
    "encourage or arouse interest or enthusiasm in.",
    "ungenerous.",
    "astonish or shock (someone) so that they are temporarily unable to react.",
    "provide evidence to support or prove the truth of.",
    "especially of a change or distinction) so delicate or precise as to be difficult to analyse or describe.",
    "the undermining of the power and authority of an established system or institution.",
    "a sulky or depressed mood.",
    "unnecessary, especially through being more than enough.",
    "take the place of (a person or thing previously in authority or use); supplant.",
    "a thing added to something else in order to complete or enhance it.",
    "the action of asking or begging for something earnestly or humbly.",
    "bad-tempered and unfriendly",
    " substitute, especially a person deputizing for another in a specific role or office.",
    "likely or liable to be influenced or harmed by a particular thing.",
    "a person who acts obsequiously towards someone important in order to gain advantage",
    "of or forming a general summary or synopsis.",
    "of or relating to or conforming to the rules of syntax",
    "to bring together or combine (separate elements) to form a whole.",
    "(of a person) reserved or uncommunicative in speech; saying little.",
    "having or showing a lack of skill and sensitivity in dealing with others or with difficult issues.",
    "showing moderation or self-restraint.",
    "expressing or intending to promote a particular cause or point of view, especially a controversial one.",
    "showing little enthusiasm",
    "the quality of using money and other resources carefully and not wastefully.",
    "showing or suffering from nervousness or a lack of confidence.",
    "free from disturbance; calm.",
    "surpass (a person or achievement).",
    "an act that goes against a law, rule, or code of conduct; an offence.",
    "not permanent.",
    "a thing of little value or importance.",
    "lacking originality or freshness; dull on account of overuse.",
    "of little value or importance.",
    "present, appearing, or found everywhere.",
    "(of a person) not highly educated or socially adept.",
    "(of a person) not tending to express feelings, especially of affection, openly.",
    "lessen the effectiveness, power, or ability of, especially gradually or insidiously.",
    "emphasize.",
    "describe or represent (something) as being smaller or less good or important than it really is.",
    "unfasten, untie, or loosen (something).",
    "impossible to understand.",
    "not able to be mistaken for anything else; very distinctive.",
    "never done or known before.",
    "(of an act, remark, or state) not thought out or planned beforehand.",
    "not attempting to impress others with an appearance of greater importance, talent, or culture than is actually possessed.",
    "(of a circumstance) not giving or indicating a good chance of success; unfavourable.",
    "(of behaviour or actions) not proper or appropriate",
    "not safe or robust; in poor condition.",
    "(of a resource) not yet exploited or used.",
    "completely and without qualification; absolutel",
    "showing or motivated by susceptibility to bribery; corrupt.",
    "speaking or representing the truth.",
    "forming a very small remnant of something that was once greater or more noticeable, remaining, surviving",
    "capable of working successfully; feasible.",
    "the action or state of keeping careful watch for possible danger or difficulties.",
    "clear (someone) of blame or suspicion.",
    "the severity or harmfulness of a disease or poison.",
    "expressing or characterized by vehement opinions; loud and forceful.",
    "(of a person) talking fluently, readily, or incessantly",
    "lacking in a required or necessary quality.",
    "feeling or showing caution about possible dangers or problems.",
    "(of a bad or harmful act) intentional; deliberate",
    "showing or characterized by quick and inventive verbal humour",
    "seek the favour, support, or custom of",
    "a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals."
  ]
  wordObj = {
    "Abandon": "complete lack of inhibition or restraint.",
    "Abrasive": "showing little concern for the feelings of others; harsh.",
    "Abreast": "up to date with the latest news, ideas, or information",
    "Abridge": "shorten (a piece of writing) without losing the sense.",
    "Abstruse": "difficult to understand; obscure.",
    "Accentuate": "to make (something) more prominent or noticeable",
    "Accord": "an official agreement or treaty.",
    "Acerbic": "sharply or bitingly critical, sarcastic, or ironic in temper, mood, or tone",
    "Acquisitive": "excessively interested in acquiring money or material things.",
    "Activism": "the policy or action of using vigorous campaigning to bring about political or social change.",
    "Acumen": "superior insight; quickness and shrewdness of judgment, especially in practical matters.",
    "Acute": "having or showing a perceptive understanding or insight; shrewd.",
    "Adroit": "clever or skillful in using the hands or mind.",
    "Adulation": "obsequious flattery; excessive admiration or praise.",
    "Aesthetic": "concerned with beauty or the appreciation of beauty.",
    "Affable": "friendly, good-natured, or easy to talk to.",
    "Affectation": "behavior, speech, or writing that is artificial and designed to impress.",
    "Aghast": "filled with horror or shock.",
    "Alacrity": "brisk and cheerful readiness.",
    "Alienate": "cause (someone) to feel isolated or estranged.",
    "Aloof": "conspicuously uninvolved and uninterested, typically through distaste.",
    "Ambiguity": "the quality of being open to more than one interpretation; inexactness.",
    "Ambivalent": "having mixed feelings or contradictory ideas about something or someone.",
    "Ameliorate": "make (something bad or unsatisfactory) better, improve",
    "Amiable": "having or displaying a friendly and pleasant manner.",
    "Amuse": "cause (someone) to find something funny; entertain.",
    "Anachronism": "belonging to a period other than that being portrayed.",
    "Antagonistic": "showing or feeling active opposition or hostility toward someone or something.",
    "Antedate": "precede in time; come before (something) in date.",
    "Antiquity": "the ancient past, especially the period before the middle ages.",
    "Antithesis": "a contrast or opposition between two things.",
    "Apathy": "lack of interest, enthusiasm, or concern.",
    "Aplomb": "complete and confident composure or self-assurance",
    "Apologist": "a person who offers an argument in defense of something controversial.",
    "Apposite": "apt in the circumstances or in relation to something.",
    "Appropriate": "take (something) for one's own use, typically without the owner's permission.",
    "Arbitrary": "based on random choice or personal whim, rather than any reason or system.",
    "Arcane": "understood by few; mysterious or secret.",
    "Arduous": "involving or requiring strenuous effort; difficult and tiring.",
    "Articulate": "(of a person or a person's words) having or showing the ability to speak fluently and coherently.",
    "Assertive": "having or showing a confident and forceful personality.",
    "Assiduous": "showing great care and perseverance.",
    "Astonish": "surprise or impress (someone) greatly.",
    "Astound": "shock or greatly surprise.",
    "Attainment": "a thing achieved, especially a skill or educational achievement.",
    "Attribute": "regard something as being caused by (someone or something).",
    "Augment": "make (something) greater by adding to it; increase.",
    "Austerity": "extreme plainness and simplicity of style or appearance.",
    "Aversion": "a strong dislike or disinclination.",
    "Avert": "prevent or ward off (an undesirable occurrence).",
    "Banal": "so lacking in originality as to be obvious and boring.",
    "Banish": "send (someone) away from a country or place as an official punishment.",
    "Bearing": "relation; relevance.",
    "Befriend": "act as a friend to (someone) by offering help or support.",
    "Beguile": "help (time) pass pleasantly.",
    "Beholden": "owing thanks or having a duty to someone in return for help or a service.",
    "Belie": "(of an appearance) fail to give a true notion or impression of (something); disguise or contradict.",
    "Bemuse": "puzzle, confuse, or bewilder (someone).",
    "Benign": "harmless, kind, gentle",
    "Betray": "unintentionally reveal; be evidence of.",
    "Bias": "prejudice in favor of or against one thing, person, or group compared with another, usually in a way considered to be unfair.",
    "Blemish": "spoil the appearance of (something) that is otherwise aesthetically perfect.",
    "Blight": "have a severely detrimental effect on.",
    "Blithe": "showing a casual and cheerful indifference considered to be callous or improper.",
    "Blunt": "(of a person or remark) uncompromisingly forthright.",
    "Bogus": "not genuine or true; fake.",
    "Bolster": "support or strengthen; prop up.",
    "Boon": "a thing that is helpful or beneficial.",
    "Braggart": "a person who boasts about achievements or possessions.",
    "Brandish": "wave or flourish (something, especially a weapon) as a threat or in anger or excitement.",
    "Brazen": "bold and without shame. endure an embarrassing or difficult situation by behaving with apparent confidence and lack of shame.",
    "Brevity": "concise and exact use of words in writing or speech.",
    "Bridle": "bring (something) under control; curb.",
    "Bucolic": "relating to the pleasant aspects of the countryside and country life.",
    "Buoyancy": "an optimistic and cheerful disposition.",
    "Calamitous": "involving calamity; catastrophic or disastrous.",
    "Callous": "feeling or showing no sympathy for others",
    "Calumny": "a false and slanderous statement.",
    "Canny": "having or showing shrewdness and good judgment, especially in money or business matters.",
    "Canonize": "treat or regard as being above reproach or of great significance.",
    "Caprice": "a sudden and unaccountable change of mood or behavior.",
    "Catastrophe": "an event causing great and often sudden damage or suffering; a disaster.",
    "Cerebral": "intellectual rather than emotional or physical.",
    "Check": "stop or slow down the progress of (something undesirable).",
    "Cherish": "protect and care for (someone) lovingly.",
    "Circumscribe": "restrict (something) within limits.",
    "Circumstantial": "pointing indirectly toward someone's guilt but not conclusively proving it.",
    "Clangor": "a continuous loud banging or ringing sound.",
    "Clearheaded": "alert and thinking logically and coherently.",
    "Clerical": "relating to the clergy.",
    "Cloak": "hide, cover, or disguise (something).",
    "Clumsy": "done awkwardly or without skill or elegance.",
    "Coalesce": "come together to form one mass or whole.",
    "Cogent": "(of an argument or case) clear, logical, and convincing.",
    "Coherent": "(of an argument, theory, or policy) logical and consistent.",
    "Collusion": "secret or illegal cooperation or conspiracy, especially in order to cheat or deceive others.",
    "Commensurate": "corresponding in size or degree; in proportion.",
    "Commonplace": "a trite saying or topic; a platitude, a usual or ordinary thing.",
    "Compel": "force or oblige (someone) to do something.",
    "Complacent": "showing smug or uncritical satisfaction with oneself or one's achievements.",
    "Complementary": "acting or serving to complete; completing.",
    "Compliance": "unworthy or excessive acquiescence.",
    "Conditional": "subject to one or more conditions or requirements being met; made or granted on certain terms.",
    "Condone": "accept and allow (behavior that is considered morally wrong or offensive) to continue.",
    "Confound": "cause surprise or confusion in (someone), especially by acting against their expectations.",
    "Consensus": "a general agreement.",
    "Conspicuous": "standing out so as to be clearly visible.",
    "Contemporary": "living or occurring at the same time.",
    "Contemptuous": "feeling or expressing angry disgust, as at something unworthy or wicked; scornful.",
    "Contend": "engage in a competition or campaign in order to win or achieve (something).",
    "Contentment": "a state of happiness and satisfaction.",
    "Conundrum": "a confusing and difficult problem or question.",
    "Convoluted": "(especially of an argument, story, or sentence) extremely complex and difficult to follow.",
    "Cope": "(of a person) deal effectively with something difficult.",
    "Copious": "abundant in supply or quantity.",
    "Corroborate": "confirm or give support to (a statement, theory, or finding).",
    "Counterfeit": "a fraudulent imitation of something else; a forgery.",
    "Counterintuitive": "contrary to intuition or to common-sense expectation (but often nevertheless true).",
    "Counterproductive": "having the opposite of the desired effect.",
    "Cow": "cause (someone) to submit to one's wishes by intimidation.",
    "Crafty": "clever at achieving one's aims by indirect or deceitful methods.",
    "Crestfallen": "sad and disappointed.",
    "Cunning": "having or showing skill in achieving one's ends by deceit or evasion.",
    "Cursory": "hasty and therefore not thorough or detailed.",
    "Curtail": "to make less by or as if by cutting off or away some part",
    "Cynical": "believing that people are motivated by self-interest; distrustful of human sincerity or integrity.",
    "Daunt": "make (someone) feel intimidated or apprehensive.",
    "Debacle": "a sudden collapse into disaster; downfall.",
    "Debase": "to reduce in value, quality, esteem, or character.",
    "Debunk": "to expose or ridicule the falseness or exaggerations of (a claim, theory, or the like).",
    "Deceit": "the act or practice of misleading, tricking, or cheating.",
    "Deceptive": "able or tending to trick or mislead.",
    "Defamatory": "causing or tending to cause injury to another's reputation; libelous or slanderous.",
    "Deferential": "respectfully submissive to the desires, opinions, or judgments of others.",
    "Deft": "capable, quick, and clever in action; skillful; dexterous.",
    "Defy": "to resist or challenge openly; act against the wishes or decrees of.",
    "Deleterious": "harmful or injurious, as to health.",
    "Delineate": "to describe or portray in precise or vivid detail.",
    "Demur": "raise doubts or objections or show reluctance.",
    "Denigrate": "criticize unfairly; disparage.",
    "Derivative": "copied, modeled on, or extracted from something else.",
    "Detrimental": "causing harm, disadvantage, or deterioration.",
    "Devious": "not the straightest, most direct way; winding; roundabout.",
    "Devolve": "(of duties or responsibility) pass to (a body or person at a lower level).",
    "Didactic": "in the manner of a teacher, particularly so as to treat someone in a patronizing way.",
    "Diffident": "modest or shy because of a lack of self-confidence.",
    "Diffuse": "spread out over a large area; not concentrated.",
    "Disaffection": "a state or feeling of being dissatisfied with the people in authority and no longer willing to support them.",
    "Disapprobation": "strong disapproval, typically on moral grounds.",
    "Discern": "to perceive, make out, or detect.",
    "Discomfit": "make (someone) feel uneasy or embarrassed.",
    "Discount": "regard (a possibility, fact, or person) as being unworthy of consideration because it lacks credibility.",
    "Discredit": "to harm the reputation of.",
    "Discrepancy": "lack of agreement; difference; inconsistency.",
    "Disentangle": "to free or become free from entanglement or involvement; extricate.",
    "Disgruntle": "to make irritably dissatisfied or discontent.",
    "Disintegrate": "to come apart; break down into component parts or fragments.",
    "Disinterested": "having or feeling no interest in something.",
    "Dislocation": "disturbance from a proper, original, or usual place or state.",
    "Dismantle": "to tear down; take apart.",
    "Disparate": "essentially different and distinct.",
    "Dispassionate": "without strong feeling or bias; calm; impartial.",
    "Dispense": "to give out or distribute.",
    "Disquiet": "lack of mental calm or peace; anxiety; uneasiness.",
    "Dissemble": "to disguise or hide behind a false semblance; conceal the true nature or state of.",
    "Disseminate": "to spread widely, as though scattering seed.",
    "Dissimilar": "not alike; different.",
    "Dissolution": "debauched living; dissipation.",
    "Distill": "extract the essential meaning or most important aspects of.",
    "Distort": "give a misleading or false account or impression of.",
    "Divergent": "deviating, differing, or diverging.",
    "Doctrinaire": "dogmatically adhering to a theory or a school of thought, regardless of its practicality.",
    "Dogmatic": "asserting beliefs and opinions as though they were proven facts.",
    "Dubious": "having or showing doubt; skeptical.",
    "Duplicity": "deceitful speech or action.",
    "Dynamism": "the quality of being characterized by vigorous activity and progress.",
    "Eclectic": "deriving ideas, style, or taste from a broad and diverse range of sources.",
    "Eclipse": "overshadow, outshine",
    "Ecstatic": "in a condition of extreme delight, overpowering emotion, or religious trance; enraptured.",
    "Efficacy": "the ability to produce desired results; effectiveness.",
    "Egoism": "the tendency to evaluate everything in relation to one's own interests; self-centeredness.",
    "Egotist": "a conceited person; braggart.",
    "Elate": "to make extremely happy or proud; cause to be in elevated spirits.",
    "Elevate": "to raise or lift up to a higher physical position.",
    "Eloquence": "skill or ability to use language that impresses or persuades.",
    "Elusive": "hard to perceive, understand, or remember.",
    "Empathy": "the ability to understand and share the feelings of another.",
    "Emulate": "to try to be the same as or better than (another person), especially by imitating.",
    "Enchant": "to put under a magic spell, or as if under a magic spell; bewitch.",
    "Endanger": "to cause to be exposed to danger.",
    "Endorse": "to approve or give support to.",
    "Enfeeble": "to take away the strength of; make feeble, as from age or disease.",
    "Engage": "occupy, attract, or involve (someone's interest or attention).",
    "Enigmatic": "puzzling, mysterious, or inexplicable.",
    "Entail": "involve (something) as a necessary or inevitable part or consequence.",
    "Entreaty": "an earnest or humble request.",
    "Entrench": "establish (an attitude, habit, or belief) so firmly that change is very difficult or unlikely.",
    "Ephemeral": "lasting for only a short period.",
    "Equitable": "characterized by fairness; just.",
    "Equivocal": "open to more than one interpretation; ambiguous.",
    "Erode": "gradually destroy or be gradually destroyed.",
    "Erratic": "not occurring predictably or consistently; unpredictable.",
    "Erroneous": "containing or based on a mistake; incorrect.",
    "Erstwhile": "of an earlier time; former.",
    "Estrange": "cause (someone) to be no longer close or affectionate to someone; alienate.",
    "Euphoric": "having or exhibiting a strong feeling of well-being or elation.",
    "Evanescent": "tending to disappear like vapor; vanishing; fleeting.",
    "Evasive": "ambiguous, tending to avoid commitment or self-revelation, especially by responding only indirectly.",
    "Exacerbate": "make (a problem, bad situation, or negative feeling) worse.",
    "Exacting": "making great demands on one's skill, attention, or other resources.",
    "Exigent": "requiring immediate attention; urgent or critical.",
    "Exotic": "attractive or striking because colorful or out of the ordinary.",
    "Expedient": "a means of attaining an end, especially one that is convenient but considered improper or immoral.",
    "Explicit": "stated fully, clearly, and without equivocation.",
    "Exploit": "make full use of and derive benefit from (a resource).",
    "Exposition": "a comprehensive description and explanation of an idea or theory.",
    "Extant": "still in existence; current; not extinct, destroyed, or lost.",
    "Extraneous": "coming from outside; foreign.",
    "Extravagance": "the act or an instance of spending excessively or imprudently.",
    "Factual": "containing or based upon real or true things.",
    "Fastidious": "very attentive to and concerned about accuracy and detail.",
    "Feckless": "weak or incompetent; ineffective.",
    "Feeble": "without strength or vigor, physically, mentally, or morally.",
    "Fester": "(of a negative feeling or a problem) becoming worse or more intense, especially through long-term neglect or indifference.",
    "Fickle": "quickly changing without reason or warning, especially in affection or allegiance; variable or capricious.",
    "Fixate": "cause (someone) to acquire an obsessive attachment to someone or something.",
    "Fleeting": "lasting for a very short time.",
    "Florid": "elaborately or excessively intricate or complicated.",
    "Flourish": "to make bold and sweeping gestures",
    "Flout": "openly disregard (a rule, law or convention).",
    "Foreground": "make (something) the most prominent or important feature.",
    "Foresight": "the ability to predict or the action of predicting what will happen or be needed in the future.",
    "Forestall": "to prevent or hinder by taking action beforehand.",
    "Forgo": "omit or decline to take (something pleasant or valuable); go without.",
    "Forsake": "to abandon or desert.",
    "Fortuitous": "happening or appearing by chance, as a coincidence.",
    "Fractious": "(typically of children) irritable and quarrelsome.",
    "Fringe": "not part of the mainstream; unconventional, peripheral, or extreme.",
    "Frivolous": "unworthy of serious consideration or merit; trivial or silly.",
    "Frugality": "prudent or sparing use of resources, especially money.",
    "Futile": "unlikely to produce or incapable of producing a desired result; ineffective; useless.",
    "Galvanize": "to stimulate into awareness or activity.",
    "Gawky": "ungainly; awkward; clumsy.",
    "Germane": "having relevance to a given matter; pertinent; significant.",
    "Global": "relating to or embracing the whole of something, or of a group of things.",
    "Gloom": "to look, feel, or act sullen or despondent",
    "Goosebumps": "a state of the skin caused by cold, fear, or excitement, in which small bumps appear on the surface as the hairs become erect.",
    "Gracious": "inclined to do what is polite, kind, right, or considerate.",
    "Gratify": "to give pleasure or satisfaction to (someone).",
    "Hackneyed": "made trite or commonplace by overuse, as an expression or phrase.",
    "Harbinger": "a person or thing that announces or signals the approach of another.",
    "Harmonious": "characterized by agreement or accord.",
    "Heed": "to give one's attention to; take notice of.",
    "Herald": "be a sign that (something) is about to happen.",
    "Heterodox": "deviating from an officially approved belief or doctrine, especially in religion.",
    "Hidebound": "unwilling or unable to change because of tradition or convention.",
    "Hindrance": "someone or something that acts as an obstacle, as to an action or goal.",
    "Homogeneity": "the quality or state of being all the same or all of the same kind.",
    "Hortatory": "urging or exciting to some course of action with strong arguments, appeals, or advice.",
    "Humdrum": "lacking variety; dull, monotonous, and commonplace.",
    "Hyperbole": "exaggerated statements or claims not meant to be taken literally.",
    "Hypocrite": "one who states or pretends to hold beliefs or principles he or she does not actually practice.",
    "Iconoclastic": "attacking or breaking away from established traditions, beliefs, or values.",
    "Illiberal": "lacking tolerance; bigoted.",
    "Illuminate": "help to clarify or explain.",
    "Imitate": "to follow the manner or pattern of; attempt to resemble; mimic.",
    "Imminent": "about to happen or likely to happen very soon.",
    "Immunity": "protection or exemption from something, especially an obligation or penalty.",
    "Immure": "to confine within or as though within walls; shut in.",
    "Immutable": "not subject to change; unchanging or unchangeable.",
    "Impair": "to weaken, damage, or cause to diminish in value or quality.",
    "Impartial": "not biased or prejudiced; even-handed or objective.",
    "Impecunious": "having little or no money.",
    "Impediment": "an obstacle or hindrance.",
    "Impenetrable": "impossible to understand.",
    "Imperative": "extremely important; urgent; unavoidable.",
    "Impetuous": "acting or done quickly and without thought or care.",
    "Impetus": "something that urges or impels; a driving force.",
    "Implicit": "essentially or very closely connected with; always to be found in.",
    "Impolitic": "not showing good sense or judgment; unwise or injudicious.",
    "Improvisation": "produce or make (something) from whatever is available.",
    "Imprudent": "not showing care for the consequences of an action; rash.",
    "Impudence": "the act or condition of being boldly disrespectful; insolence.",
    "Impulsive": "motivated by spontaneous wishes and needs rather than careful thought.",
    "Inalienable": "not subject to transfer, surrender, or removal, especially one's rights as a citizen.",
    "Inarticulate": "unable to speak distinctly or express oneself clearly.",
    "Incendiary": "tending to stir up conflict.",
    "Incensed": "very angry; enraged.",
    "Incongruous": "not in harmony or keeping with the surroundings or other aspects of something.",
    "Inconsequential": "having no significant effect or result; not important.",
    "Inconsiderable": "unimportant or insignificant.",
    "Indebted": "obligated to another person or persons, as for money or favors.",
    "Indecision": "inability or unwillingness to make a decision.",
    "Indecorous": "not in keeping with good taste and propriety; improper.",
    "Indefatigable": "(of a person or their efforts) persisting tirelessly.",
    "Indemnify": "to make compensation to for loss, damage, or expense incurred.",
    "Indifferent": "lacking interest or concern; not caring.",
    "Indiscernible": "impossible to see or clearly distinguish.",
    "Indolent": "wanting to avoid activity or exertion; lazy.",
    "Industrious": "diligent and hard-working.",
    "Inestimable": "too great to calculate.",
    "Infallible": "incapable of error.",
    "Informed": "having or showing knowledge of a particular subject or situation.",
    "Ingenious": "(of a person) clever, original, and inventive.",
    "Inhibit": "to hold back, restrain, prevent, or tend to do so.",
    "Inimical": "unfriendly; hostile.",
    "Injudicious": "lacking in or poor in judgment; rash or unwise.",
    "Innocuous": "not capable of causing damage; harmless.",
    "Inscrutable": "impossible to comprehend or interpret; mysterious.",
    "Insightful": "having or showing an accurate and deep understanding; perceptive.",
    "Insipid": "having a bland or uninteresting flavor; tasteless.",
    "Insolence": "rude or impudent behavior or speech.",
    "Integrate": "to bring together and blend into a whole.",
    "Intelligible": "capable of being clearly understood; comprehensible.",
    "Interchangeable": "of two things, able to be put or used in place of each other.",
    "Intermediary": "a person who acts as an agent or mediator between persons, groups, or the like; go-between.",
    "Interminable": "endless or seemingly endless; monotonously long.",
    "Interweave": "blend closely.",
    "Intimately": "in a way that involves detailed knowledge.",
    "Intractable": "not easily controlled, managed, or persuaded.",
    "Intransigent": "refusing to alter an idea or a position in response to others' wishes; uncompromising.",
    "Intrigue": "to strongly draw the interest of; puzzle; fascinate.",
    "Intrinsic": "being essential to or of the nature of a thing; inherent.",
    "Invaluable": "having a worth too great to estimate or measure; priceless.",
    "Inveigle": "to entice or ensnare by clever talk or flattery.",
    "Invigorate": "to fill with energy, strength, or life.",
    "Involved": "difficult to comprehend; complicated.",
    "Irascible": "easily angered or irritated; short-tempered.",
    "Irksome": "causing annoyance; bothersome or tiresome.",
    "Ironic": "happening in the opposite way to what is expected, and typically causing wry amusement because of this.",
    "Irrefutable": "impossible to disprove; indisputable.",
    "Irremediable": "impossible to cure, repair, or correct.",
    "Irresolute": "showing or feeling hesitancy; uncertain.",
    "Jettison": "throw or drop (something) from an aircraft or ship.",
    "Judicious": "characterized by or using sound judgment; wise; prudent.",
    "Juxtaposition": "the fact of two things being seen or placed close together with contrasting effect.",
    "Keen": "extremely sharp; able to cut readily and finely.",
    "Kindred": "similar in kind; related.",
    "Laborious": "requiring considerable effort or perseverance.",
    "Lament": "a passionate expression of grief or sorrow.",
    "Latitude": "scope for freedom of action or thought.",
    "Laudable": "worthy of praise.",
    "Lax": "not rigorous, strict, or careful; loose; lenient.",
    "Layperson": "a person without professional or specialized knowledge in a particular subject.",
    "Lionize": "to view or treat (someone) as a celebrity or extraordinary person.",
    "Long-Winded": "speaking or writing at too great a length, especially in a dull or tiresome way; verbose.",
    "Loquacious": "given to talking much or excessively; garrulous.",
    "Lucid": "easy to understand; articulate; clear.",
    "Lucrative": "producing monetary gain; profitable.",
    "Lure": "to attract, as by a desirable quality.",
    "Lurid": "sensational; shocking or dramatic.",
    "Magnanimity": "generosity or willingness to forgive.",
    "Makeshift": "a temporary or improvised arrangement.",
    "Maladroit": "not skillful; clumsy; tactless.",
    "Malign": "to speak badly of; defame; slander.",
    "Malignant": "evil or injurious in intent, effect, or character.",
    "Malleable": "easily influenced; pliable.",
    "Manacle": "restrain, hinder",
    "Manipulate": "control or influence (a person or situation) cleverly, unfairly, or unscrupulously.",
    "Marginalize": "to exclude or treat as being of no importance, especially so as to divert attention from.",
    "Mask": "conceal (something) from view.",
    "Materialize": "become actual fact; happen.",
    "Meager": "low in quantity, extent, strength, or richness; scanty or feeble.",
    "Melding": "blend; combine.",
    "Menace": "that which poses a danger or threatens injury or harm; threat.",
    "Mercurial": "volatile in temper; changeable; fickle.",
    "Meticulous": "carefully attentive to every small detail; painstaking.",
    "Mimic": "to copy or imitate, often playfully or as part of a learning process.",
    "Misnomer": "an incorrect or inappropriate name.",
    "Mitigate": "to lessen the force, severity, or impact of.",
    "Modish": "being in or according to current fashion or style; fashionable.",
    "Monotony": "lack of variety and interest; tedious repetition and routine.",
    "Morbid": "in an unhealthy, gloomy mental state; preoccupied with sickness, abnormality, or death.",
    "Mortify": "to subject (someone) to extreme embarrassment, shame, or humiliation.",
    "Mounting": "grow larger or more numerous.",
    "Multifaceted": "having several aspects or stages; complex or various.",
    "Mundane": "of or pertaining to what is common and everyday; ordinary; commonplace.",
    "Murky": "not fully explained or understood, especially with concealed dishonesty or immorality.",
    "Naive": "(of a person or action) showing a lack of experience, wisdom, or judgment.",
    "Narcissism": "excessive interest in or admiration of oneself and one's physical appearance.",
    "Narrative": "an account, description, or story, or the oral or written work containing such material.",
    "Nascent": "coming into being or starting to develop.",
    "Nettles": "irritate or annoy (someone).",
    "Nonchalant": "not showing excitement or anxiety; coolly confident, unflustered, or unworried;casually indifferent.",
    "Normative": "establishing, relating to, or deriving from a standard or norm, especially of behavior.",
    "Novel": "new or unusual in an interesting way.",
    "Noxious": "harmful, dangerous, or destructive, especially to health.",
    "Obdurate": "stubbornly refusing to change one's opinion or course of action.",
    "Objurgate": "to criticize sharply; rebuke vehemently; berate.",
    "Obligate": "to bind legally or morally; constrain.",
    "Obscure": "not important or well known.",
    "Obsequious": "obedient or attentive to an excessive or servile degree, fawning",
    "Obsolete": "no longer produced or used; out of date.",
    "Obstinate": "holding stubbornly to one's own ideas or purposes; unwilling to change.",
    "Obviate": "avoid; prevent.",
    "Omnipresent": "existing in all places at any given time.",
    "Omniscient": "infinite in knowledge; all-knowing.",
    "Opportunism": "the taking of opportunities as and when they arise, regardless of planning or principle.",
    "Optimistic": "expecting or tending to expect favorable outcomes.",
    "Opulent": "having or displaying wealth or richness.",
    "Original": "created directly and personally by a particular artist; not a copy or imitation.",
    "Outmoded": "no longer in keeping with current standards or practices; obsolete.",
    "Overly": "excessively",
    "Overshadow": "appear much more prominent or important than.",
    "Overstate": "to inflate the importance of; exaggerate.",
    "Panacea": "a remedy or solution for all diseases, ills, or difficulties; cure-all.",
    "Panache": "a confidently stylish, dashing, or flamboyant manner.",
    "Partial": "favoring one side in a dispute above the other; biased.",
    "Partiality": "unfair bias in favor of one thing or person compared with another; favoritism.",
    "Partisan": "devoted to or favoring a particular cause, group, political party, or the like.",
    "Passable": "just good enough to be acceptable; satisfactory.",
    "Pastoral": "of or relating to the country or country life; rural.",
    "Patent": "easily recognizable; obvious.",
    "Peculiarity": "the state or fact of being odd or strange.",
    "Pedestrian": "lacking inspiration or excitement; dull.",
    "Pejorative": "expressing contempt or disapproval.",
    "Pellucidity": "lucid in style or meaning; easily understood.",
    "Penchant": "a strong or habitual liking for something or tendency to do something.",
    "Penetrate": "be fully understood or realized by someone.",
    "Penitent": "feeling or showing sorrow and regret for having done wrong; repentant.",
    "Perfunctory": "done quickly and as a matter of routine; performed without care.",
    "Peripheral": "of secondary or minor importance; marginal.",
    "Pernicious": "having a very harmful or fatal effect; injurious, deadly, or destructive.",
    "Perseverance": "persistence in doing something despite difficulty or delay in achieving success.",
    "Persistence": "firm or obstinate continuance in a course of action in spite of difficulty or opposition.",
    "Personify": "to be a perfect or typical example of; embody.",
    "Perspicacity": "keenness of mental perception or grasp; astuteness.",
    "Pessimism": "the belief that events will turn out badly; tendency to expect the worst.",
    "Phlegmatic": "not given to shows of emotion or interest; slow to excite.",
    "Picturesque": "visually pleasing, enchanting, or unusual; suggestive of a painting.",
    "Pithy": "exactly and concisely appropriate; effective; forceful.",
    "Pivotal": "critically important or crucial; on which something is contingent.",
    "Placid": "calm, smooth, or tranquil.",
    "Plastic": "not genuine; artificial or unnatural.",
    "Plod": "to move slowly or heavily, as if with weariness or reluctance; trudge.",
    "Polemic": "a strong verbal or written attack on someone or something.",
    "Portend": "be a sign or warning that (something, especially something momentous or calamitous) is likely to happen.",
    "Pragmatism": "a practical approach to problems and issues.",
    "Precarious": "dependent on chance; uncertain.",
    "Precedence": "priority in importance, order, or rank.",
    "Precocious": "(of a child) having developed certain abilities or inclinations at an earlier age than is usual or expected.",
    "Predicament": "a difficult, unpleasant, or embarrassing situation.",
    "Predominant": "having or exerting control or power.",
    "Preeminent": "surpassing all others; very distinguished in some way.",
    "Premonition": "a strong feeling that something is about to happen, especially something unpleasant.",
    "Presage": "be a sign or warning of (an imminent event, typically an unwelcome one).",
    "Prescience": "the fact of knowing something in advance; foreknowledge.",
    "Pressing": "requiring quick or immediate action or attention.",
    "Presume": "take for granted that something exists or is the case.",
    "Pretension": "the use of affectation to impress; ostentatiousness.",
    "Pretentious": "attempting to impress by affecting greater importance or merit than is actually possessed.",
    "Prevalent": "widespread in a particular area or at a particular time.",
    "Prevaricate": "speak or act in an evasive way.",
    "Pristine": "in its original condition; unspoilt.",
    "Probity": "the quality of having strong moral principles; honesty and decency.",
    "Prodigal": "spending money or resources freely and recklessly; wastefully extravagant.",
    "Profligate": "recklessly extravagant or wasteful in the use of resources.",
    "Profound": "(of a subject or idea) demanding deep study or thought.",
    "Prolix": "(of speech or writing) using or containing too many words; tediously lengthy.",
    "Promulgate": "promote or make widely known (an idea or cause).",
    "Propagate": "spread and promote (an idea, theory, etc.) widely.",
    "Prophetic": "accurately predicting what will happen in the future.",
    "Propped": "support or keep in position.",
    "Prosaic": "commonplace",
    "Provincial": "limited in outlook; narrow-minded.",
    "Provoke": "stimulate or give rise to (a reaction or emotion, typically a strong or unwelcome one) in someone.",
    "Proxy": "a person authorized to act on behalf of another.",
    "Prudent": "acting with or showing care and thought for the future.",
    "Pugnacious": "eager or quick to argue, quarrel, or fight.",
    "Punctilious": "showing great attention to detail or correct behaviour.",
    "Puzzle": "cause (someone) to feel confused because they cannot understand something.",
    "Quandary": "a state of perplexity or uncertainty over what to do in a difficult situation.",
    "Quirky": "characterized by peculiar or unexpected traits.",
    "Quixotic": "exceedingly idealistic; unrealistic and impractical.",
    "Quotidian": "of or occurring every day; daily.",
    "Rallying": "the action or process of coming together to support a person or cause.",
    "Ramble": "talk or write at length in a confused or inconsequential way.",
    "Rationalize": "attempt to explain or justify (behaviour or an attitude) with logical reasons, even if these are not appropriate.",
    "Recondite": "(of a subject or knowledge) little known; abstruse.",
    "Recrudesce": "to break out or appear again after a period of dormancy",
    "Redemption": "the action of saving or being saved from sin, error, or evil.",
    "Redouble": "make or become much greater, more intense, or more numerous.",
    "Redundant": "unnecessarily repetitive.",
    "Refuge": "the state of being safe or sheltered from pursuit, danger, or difficulty.",
    "Rein": "keep under control; restrain.",
    "Rejuvenate": "give new energy or vigour to; revitalize.",
    "Relish": "great enjoyment.",
    "Remedial": "giving or intended as a remedy or cure.",
    "Replicate": "make an exact copy of; reproduce.",
    "Repudiate": "refuse to accept; reject.",
    "Residual": "remaining after the greater part or quantity has gone.",
    "Resolute": "admirably purposeful, determined, and unwavering.",
    "Restive": "(of a person) unable to remain still, silent, or submissive, especially because of boredom or dissatisfaction.",
    "Restrain": "prevent (someone or something) from doing something; keep under control or within limits.",
    "Resurgent": "increasing or reviving after a period of little activity, popularity, or occurrence.",
    "Reverence": "deep respect for someone or something.",
    "Rhapsody": "an effusively enthusiastic or ecstatic expression of feeling.",
    "Ridicule": "subject to contemptuous and dismissive language or behaviour.",
    "Row": "dispute",
    "Ruinous": "disastrous or destructive.",
    "Ruminate": "think deeply about something.",
    "Salubrious": "health-giving; healthy.",
    "Sanguine": "optimistic or positive, especially in an apparently bad or difficult situation.",
    "Sartorial": "relating to tailoring, clothes, or style of dress.",
    "Scanty": "small or insufficient in quantity or amount.",
    "Scathe": "harm; injure.",
    "Schism": "a split or division between strongly opposed sections or parties, caused by differences in opinion or belief.",
    "Scintillating": "brilliantly and excitingly clever or skillful.",
    "Scornful": "feeling or expressing contempt or derision.",
    "Scrupulous": "adhering strictly to standards of ethics or morality; punctilious.",
    "Scrutinize": "examine or inspect closely and thoroughly.",
    "Scuffle": "to take part in a brief, confused fight among a few people.",
    "Flattery": "excessive and insincere praise, given especially to further one's own interests.",
    "Self-Righteous": "having or characterized by a certainty, especially an unfounded one, that one is totally correct or morally superior.",
    "Serendipity": "the occurrence and development of events by chance in a happy or beneficial way.",
    "Sham": "an imitation that is passed as genuine; counterfeit.",
    "Shirk": "avoid or neglect (a duty or responsibility).",
    "Shrewd": "having or showing sharp powers of judgement; astute.",
    "Sinister": "giving the impression that something harmful or evil is happening or will happen.",
    "Skeptic": "a person inclined to question or doubt accepted opinions.",
    "Skittish": "nervous or excitable; easily scared",
    "Slighted": "insult (someone) by treating or speaking of them without proper respect or attention.",
    "Snare": "catch or trap (someone).",
    "Sparing": "moderate; economical.",
    "Sporadic": "occurring at irregular intervals or only in a few places; scattered or isolated.",
    "Spurious": "not being what it purports to be; false or fake.",
    "Stanched": "stop or restrict (a flow of blood) from a wound.",
    "Staple": "main or important, especially in terms of consumption.",
    "Startling": "very surprising, astonishing, or remarkable.",
    "Stigmatize": "describe or regard as worthy of disgrace or great disapproval.",
    "Stimulate": "encourage or arouse interest or enthusiasm in.",
    "Stingy": "ungenerous.",
    "Stun": "astonish or shock (someone) so that they are temporarily unable to react.",
    "Substantiate": "provide evidence to support or prove the truth of.",
    "Subtle": "especially of a change or distinction) so delicate or precise as to be difficult to analyse or describe.",
    "Subversion": "the undermining of the power and authority of an established system or institution.",
    "Sullen": "a sulky or depressed mood.",
    "Superfluous": "unnecessary, especially through being more than enough.",
    "Supersede": "take the place of (a person or thing previously in authority or use); supplant.",
    "Supplement": "a thing added to something else in order to complete or enhance it.",
    "Supplication": "the action of asking or begging for something earnestly or humbly.",
    "Surly": "bad-tempered and unfriendly",
    "Surrogate": " substitute, especially a person deputizing for another in a specific role or office.",
    "Susceptible": "likely or liable to be influenced or harmed by a particular thing.",
    "Sycophant": "a person who acts obsequiously towards someone important in order to gain advantage",
    "Synoptic": "of or forming a general summary or synopsis.",
    "Syntactical": "of or relating to or conforming to the rules of syntax",
    "Synthesize": "to bring together or combine (separate elements) to form a whole.",
    "Taciturn": "(of a person) reserved or uncommunicative in speech; saying little.",
    "Tactless": "having or showing a lack of skill and sensitivity in dealing with others or with difficult issues.",
    "Temperate": "showing moderation or self-restraint.",
    "Tendentious": "expressing or intending to promote a particular cause or point of view, especially a controversial one.",
    "Tepid": "showing little enthusiasm",
    "Thrift": "the quality of using money and other resources carefully and not wastefully.",
    "Timorous": "showing or suffering from nervousness or a lack of confidence.",
    "Tranquil": "free from disturbance; calm.",
    "Transcend": "surpass (a person or achievement).",
    "Transgression": "an act that goes against a law, rule, or code of conduct; an offence.",
    "Transitory": "not permanent.",
    "Trifle": "a thing of little value or importance.",
    "Trite": "lacking originality or freshness; dull on account of overuse.",
    "Trivial": "of little value or importance.",
    "Ubiquitous": "present, appearing, or found everywhere.",
    "Uncultivated": "(of a person) not highly educated or socially adept.",
    "Undemonstrative": "(of a person) not tending to express feelings, especially of affection, openly.",
    "Undermine": "lessen the effectiveness, power, or ability of, especially gradually or insidiously.",
    "Underscore": "emphasize.",
    "Understate": "describe or represent (something) as being smaller or less good or important than it really is.",
    "Undo": "unfasten, untie, or loosen (something).",
    "Unintelligible": "impossible to understand.",
    "Unmistakable": "not able to be mistaken for anything else; very distinctive.",
    "Unprecedented": "never done or known before.",
    "Unpremeditated": "(of an act, remark, or state) not thought out or planned beforehand.",
    "Unpretentious": "not attempting to impress others with an appearance of greater importance, talent, or culture than is actually possessed.",
    "Unpropitious": "(of a circumstance) not giving or indicating a good chance of success; unfavourable.",
    "Unseemly": "(of behaviour or actions) not proper or appropriate",
    "Unsound": "not safe or robust; in poor condition.",
    "Untapped": "(of a resource) not yet exploited or used.",
    "Utterly": "completely and without qualification; absolutel",
    "Venal": "showing or motivated by susceptibility to bribery; corrupt.",
    "Veracious": "speaking or representing the truth.",
    "Vestigial": "forming a very small remnant of something that was once greater or more noticeable, remaining, surviving",
    "Viable": "capable of working successfully; feasible.",
    "Vigilance": "the action or state of keeping careful watch for possible danger or difficulties.",
    "Vindicate": "clear (someone) of blame or suspicion.",
    "Virulence": "the severity or harmfulness of a disease or poison.",
    "Vociferous": "expressing or characterized by vehement opinions; loud and forceful.",
    "Voluble": "(of a person) talking fluently, readily, or incessantly",
    "Wanting": "lacking in a required or necessary quality.",
    "Wary": "feeling or showing caution about possible dangers or problems.",
    "Wilful": "(of a bad or harmful act) intentional; deliberate",
    "Witty": "showing or characterized by quick and inventive verbal humour",
    "Woo": "seek the favour, support, or custom of",
    "Zealot": "a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals."
  }

  url = `https://docs.google.com/spreadsheets/d/e/2PACX-1vS6gxiJgtR02vrPodQZQmyMoW9E3Aa8O2qxSJKOU5qpfZW3HhoXh1wFhd3M3rj-Cd3fcoLrFHE-SmkB/pub?output=csv`;
  constructor() { }

  ngOnInit(): void {
    this.otherData();
  }

  async otherData() {
    const options = {
      method: 'GET',
      headers: { 'content-type': 'text/csv;charset=UTF-8' }
    }
    try {
      const res = await fetch(this.url, options);
      if (res.status === 200) {
        const sheetData: string = await res.text();
        const jsonArray = await csv().fromString(sheetData);
        jsonArray.forEach(obj => {
          this.wordObj[obj['word']] = obj['meaning'];
        });
      } else {
        console.log(`Error code ${res.status}`);
      }
    } catch (err) {
      console.log(err)
    }
  }


  // Preserve original property order
  originalOrder = (a: any, b: any): number => {
    return 0;
  }

  // Order by ascending property value
  valueAscOrder = (a: any, b: any): number => {
    return a.value.localeCompare(b.value);
  }

  keyAscOrder = (a: any, b: any): number => {
    return a.key < b.key ? -1 : (b.key > a.key ? 1 : 0);
  }

  // Order by descending property key
  keyDescOrder = (a: any, b: any): number => {
    return a.key > b.key ? -1 : (b.key > a.key ? 1 : 0);
  }

  get sortOrder() {
    const sortType: 'keyDescOrder' | 'valueAscOrder' | 'originalOrder' | 'keyAscOrder' = this.order;
    return this[sortType];
  }

  sortTable() {
    if (this.order == 'originalOrder') this.order = 'keyAscOrder';
    else if (this.order == 'keyAscOrder') this.order = 'valueAscOrder';
    else if (this.order == 'valueAscOrder') this.order = 'keyDescOrder';
    else this.order = 'originalOrder';
  }
}
